language: node_js
node_js:
  - '8'
  - '10'
  - '11'

branches:
  only:
    - master
    - gh-pages

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_install:
  - rvm install 2.5.0

install:
  - npm install
  - gem install html-proofer

script:
  - bundle exec jekyll build
  - npm test
  - htmlproofer --url-ignore "/talk.jekyllrb.com/" ./_site

sudo: false
